version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: rescon-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-rescon}
      POSTGRES_USER: ${POSTGRES_USER:-rescon}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-rescon}
    ports:
      - "3003:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
