version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: rescon-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-rescon}
      POSTGRES_USER: ${POSTGRES_USER:-rescon}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-rescon}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - common-net

  backend:
    image: sahancrk/rescon-server:2.0
    container_name: rescon-server
    # build:
    #   context: ./backend/
    #   dockerfile: Dockerfile
    #   no_cache: true
    # environment:
    #   PORT: 3333
    #   UI: rescon-postgres
    #   DB_HOST: rescon-postgres
    #   DB_PORT: 5432
    #   DB_NAME: rescon
    #   DB_USER: rescon
    #   DB_PASSWORD: rescon
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    networks:
      - common-net

  frontend:
    image: sahancrk/rescon-ui:2.3
    container_name: rescon-ui
    # build:
    #   context: ./frontend/
    #   dockerfile: Dockerfile
    #   no_cache: true
    # environment:
    #   API: rescon-server
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres-data:

networks:
  common-net: {}