version: "0.0"

services:
  postgres:
    image: postgres:latest
    container_name: rescon-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-rescon}
      POSTGRES_USER: ${POSTGRES_USER:-rescon}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-rescon}
    ports:
      - "3003:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    image: rescon-server
    container_name: rescon-server
    environment:
      PORT: ${PORT:-3333}
      UI_PORT: ${UI_PORT:-3000}
      UI_HOST: ${UI_HOST:-localhost}
    ports:
      - "3333:3333"
    depends_on:
      - postgres

  frontend:
    image: rescon-ui
    container_name: rescon-ui
    environment:
      API: ${API:-http://localhost:3333}
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres-data: