version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: rescon-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-rescon}
      POSTGRES_USER: ${POSTGRES_USER:-rescon}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-rescon}
    ports:
      - "3003:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    image: your-nestjs-image # Replace with your actual NestJS Docker image
    container_name: rescon-backend
    environment:
      PORT: ${PORT:-3333}
    ports:
      - "3333:3333"
    depends_on:
      - postgres

  frontend:
    image: your-nextjs-image # Replace with your actual Next.js Docker image
    container_name: rescon-frontend
    environment:
      SERVER: ${SERVER:-http://localhost:3333}
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres-data: