version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: rescon-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-rescon}
      POSTGRES_USER: ${POSTGRES_USER:-rescon}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-rescon}
    ports:
      - "5000:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - common-net

  backend:
    image: sahancrk/rescon-server:1.0
    container_name: rescon-server
    environment:
      PORT: 3333
      UI: http://host.docker.internal:3000
      DB_HOST: host.docker.internal
      DB_PORT: 5000
      DB_NAME: rescon
      DB_USER: rescon
      DB_PASSWORD: rescon
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    networks:
      - common-net

  frontend:
    image: sahancrk/rescon-ui:1.0
    container_name: rescon-ui
    environment:
      API: http://host.docker.internal:3333
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres-data:

networks:
  common-net: {}