version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: rescon-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-rescon}
      POSTGRES_USER: ${POSTGRES_USER:-rescon}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-rescon}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - common-net

  backend:
    image: sahancrk/rescon-server:3.0
    container_name: rescon-server
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    networks:
      - common-net

  frontend:
    image: sahancrk/rescon-ui:3.1
    container_name: rescon-ui
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres-data:

networks:
  common-net: {}